### ISSUE TITLE
training fails

### ISSUE THREAD

**Issue by galsk87** [rowanz/neural-motifs#22]
running the next command :+1: 
python3 ./models/train_rels.py -m sgcls -model motifnet -order leftright -nl_obj 2 -nl_edge 4 -b 6 -clip 5 \
        -p 100 -hidden_dim 512 -pooling_dim 4096 -lr 1e-3 -ngpu 1 -ckpt checkpoints/vgdet/vg-24.tar \
        -save_dir checkpoints/motifnet2 -nepoch 50 -use_bias
 and getting the next error, did you encounter this error?
Training starts now!
Traceback (most recent call last):
  File "./models/train_rels.py", line 199, in <module>
    rez = train_epoch(epoch)
  File "./models/train_rels.py", line 110, in train_epoch
    tr.append(train_batch(batch, verbose=b % (conf.print_interval*10) == 0)) #b == 0))
  File "./models/train_rels.py", line 142, in train_batch
    result = detector[b]
  File "/home/sgalk87/neural-motifs/lib/rel_model.py", line 593, in __getitem__
    return self(*batch[0])
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sgalk87/neural-motifs/lib/rel_model.py", line 538, in forward
    boxes.data, result.boxes_all)
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sgalk87/neural-motifs/lib/rel_model.py", line 333, in forward
    box_priors=box_priors,
  File "/home/sgalk87/neural-motifs/lib/rel_model.py", line 221, in edge_ctx
    obj_embed2 = self.obj_embed2(obj_preds)
  File "/home/sgalk87/neural-motifs/lib/rel_model.py", line 221, in edge_ctx
    obj_embed2 = self.obj_embed2(obj_preds)
  File "/usr/lib/python3.5/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/pudb/debugger.py", line 187, in dispatch_line
    self.user_line(frame)
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/pudb/debugger.py", line 408, in user_line
    self.interaction(frame)
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/pudb/debugger.py", line 376, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/pudb/debugger.py", line 2118, in call_with_ui
    return f(*args, **kwargs)
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/pudb/debugger.py", line 2362, in interaction
    self.event_loop()
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/pudb/debugger.py", line 2322, in event_loop
    keys = self.screen.get_input()
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 336, in get_input
    keys, raw = self.parse_input(None, None, self.get_available_raw_input())
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 436, in get_available_raw_input
    codes = self._get_gpm_codes() + self._get_keyboard_codes()
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 510, in _get_keyboard_codes
    code = self._getch_nodelay()
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 644, in _getch_nodelay
    return self._getch(0)
  File "/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 554, in _getch
    return ord(os.read(self._term_input_file.fileno(), 1))
TypeError: ord() expected a character, but string of length 0 found

**Comment by rowanz** [comment]
No clue what’s going on, the error seems to be in the debugger rather than
in the code...

**Comment by galsk87** [comment]
Please take a look at the next comment i left.

**Comment by rowanz** [comment]
It doesn’t look like you posted more than 1 comment...

**Comment by galsk87** [comment]
Training starts now!



Traceback (most recent call last):
  File "./models/train_rels.py", line 200, in <module>
    rez = train_epoch(epoch)
  File "./models/train_rels.py", line 111, in train_epoch
    tr.append(train_batch(batch, verbose=b % (conf.print_interval*10) ==
0)) #b == 0))
  File "./models/train_rels.py", line 143, in train_batch
    result = detector[b]
  File "/home/sgalk87/neural-motifs/lib/rel_model.py", line 591, in
__getitem__
    return self(*batch[0])
  File
"/home/sgalk87/neural-motifs/venv/lib/python3.5/site-packages/torch/nn/modules/module.py",
line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sgalk87/neural-motifs/lib/rel_model.py", line 568, in forward
    ), 1))
RuntimeError: The size of tensor a (38) must match the size of tensor b
(51) at non-singleton dimension 1

**Comment by rowanz** [comment]
in my version, lib.rel_model has 560 lines, not 568. so I don't know where you're getting the error.
