### ISSUE TITLE
It is seems that the pretrained detector checkpoint is not available

### ISSUE THREAD

**Issue by sim-l3** [rowanz/neural-motifs#31]
I have downloaded the pretrained detector checkpoint many times, However, the error shows that the archive is corrupted.

**Comment by sim-l3** [comment]
Thanks for your reply. Could you help me to figure it out when I run ./script/pretrain_detector.sh?


THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THC/generic/THCTensorMathPairwise.cu line=21 error=48 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "models/train_detector.py", line 209, in <module>
    rez = train_epoch(epoch)
  File "models/train_detector.py", line 65, in train_epoch
    tr.append(train_batch(batch))
  File "models/train_detector.py", line 98, in train_batch
    result = detector[b]
  File "/home/sim/Desktop/neural-motifs-master/lib/object_detector.py", line 417, in __getitem__
    outputs = nn.parallel.parallel_apply(replicas, [batch[i] for i in range(self.num_gpus)])
  File "/home/sim/anaconda3/envs/torch3.0/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
  File "/home/sim/anaconda3/envs/torch3.0/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 42, in _worker
    output = module(*input, **kwargs)
  File "/home/sim/anaconda3/envs/torch3.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sim/Desktop/neural-motifs-master/lib/object_detector.py", line 297, in forward
    gt_classes, gt_rels, train_anchor_inds, proposals=proposals)
  File "/home/sim/Desktop/neural-motifs-master/lib/object_detector.py", line 272, in get_boxes
    return fn(*args, **kwargs)
  File "/home/sim/Desktop/neural-motifs-master/lib/object_detector.py", line 157, in rpn_boxes
    post_nms_topn=2000 if self.training and self.mode == 'rpntrain' else 1000,
  File "/home/sim/Desktop/neural-motifs-master/lib/object_detector.py", line 597, in roi_proposals
    pre_nms_topn=pre_nms_topn, post_nms_topn=post_nms_topn)
  File "/home/sim/Desktop/neural-motifs-master/lib/object_detector.py", line 607, in filter_roi_proposals
    nms_thresh=nms_thresh,
  File "/home/sim/Desktop/neural-motifs-master/lib/fpn/nms/functions/nms.py", line 24, in apply_nms
    keep.append(keep_im + s)
  File "/home/sim/anaconda3/envs/torch3.0/lib/python3.6/site-packages/torch/tensor.py", line 293, in __add__
    return self.add(other)
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THC/generic/THCTensorMathPairwise.cu:21

**Comment by sim-l3** [comment]
I have found the solution in the closed issue.

**Comment by wzw1998** [comment]
> 我在已解决的问题中找到了解决方案。

how can you solute this problem？
