### ISSUE TITLE
How to use the downloaded pretrain detector checkpoint? 

### ISSUE THREAD

**Issue by rrryan2016** [rowanz/neural-motifs#59]
Hey there, 

I got a problem in step 3.

when I use the command `bash pretrain_detector.sh`, it came out as below, 

~~~~~~~~ Hyperparameters used: ~~~~~~~
coco : False
ckpt :
det_ckpt :
save_dir : checkpoints/vgdet
num_gpus : 3
num_workers : 3
lr : 0.001
batch_size : 6
val_size : 5000
l2 : 0.0001
clip : 5.0
print_interval : 100
mode : sgdet
model : motifnet
old_feats : False
order : confidence
cache :
gt_box : False
adam : False
test : False
multi_pred : False
num_epochs : 50
use_resnet : False
use_proposals : False
nl_obj : 1
nl_edge : 2
hidden_dim : 256
pooling_dim : 4096
pass_in_obj_feats_to_decoder : False
pass_in_obj_feats_to_edge : False
rec_dropout : 0.1
use_bias : False
use_tanh : False
limit_vision : False
Traceback (most recent call last):
  File "/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/models/train_detector.py", line 22, in <module>
    conf = ModelConfig()
  File "/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/config.py", line 130, in __init__
    os.mkdir(self.save_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/media/nopanic/DATA/AnExperiment/NeuralMotifs/neural-motifs-master/checkpoints/vgdet' 

Then I downloaded the pretrain detector checkpoint as the link provided in step 3 as well.

 I read some other issues:
https://github.com/rowanz/neural-motifs/issues/13
https://github.com/rowanz/neural-motifs/issues/31

But I still have no idea to use the downloaded checkpoint, and I cannot pretty understand your words "Loading it into the model should work".

Thanks in Advance !

Wenzhe Liu

**Comment by rrryan2016** [comment]
I probably solved it by create a folder named `checkpoint` and another `vgdet` under it. lol :P

**Comment by rowanz** [comment]
oh awesome! sorry for the delay. yeah you need to update the paths in `config.py` accordingly - glad that worked :)
