### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_bbox)

### ISSUE THREAD

**Issue by BetterZhouXu** [rowanz/neural-motifs#75]
Does someone encountered this problem? Google says I should use python3 envs to make relevant files, but it didn't work
Traceback (most recent call last):
  File "models/eval_rels.py", line 2, in <module>
    from dataloaders.visual_genome import VGDataLoader, VG
  File "/mnt/md0/xuelm/project/neural-motifs/dataloaders/visual_genome.py", line 14, in <module>
    from dataloaders.blob import Blob
  File "/mnt/md0/xuelm/project/neural-motifs/dataloaders/blob.py", line 4, in <module>
    from lib.fpn.anchor_targets import anchor_target_layer
  File "/mnt/md0/xuelm/project/neural-motifs/lib/fpn/anchor_targets.py", line 12, in <module>
    from lib.fpn.box_intersections_cpu.bbox import bbox_overlaps
ImportError: dynamic module does not define module export function (PyInit_bbox)

**Comment by BetterZhouXu** [comment]
after some hard works, solved the problem.
due to the cython compiling and python package.

**Comment by william-han-hri** [comment]
@BetterZhouXu  Which cython version are you using?
