### ISSUE TITLE
a ModuleNotFoundError

### ISSUE THREAD

**Issue by aishamina** [rowanz/neural-motifs#80]
Excuses me.When I run" train_models_sgcls.sh 2"，it goes wrong

Traceback (most recent call last):
  File "/home/lijiayi/neural-motifs-master/models/train_rels.py", line 27, in <module>
    from lib.rel_model import RelModel
  File "/home/lijiayi/neural-motifs-master/lib/rel_model.py", line 17, in <module>
    from lib.lstm.decoder_rnn import DecoderRNN
  File "/home/lijiayi/neural-motifs-master/lib/lstm/decoder_rnn.py", line 10, in <module>
    from .highway_lstm_cuda.alternating_highway_lstm import block_orthogonal
  File "/home/lijiayi/neural-motifs-master/lib/lstm/highway_lstm_cuda/alternating_highway_lstm.py", line 8, in <module>
    from overrides import overrides
ModuleNotFoundError: No module named 'overrides'

Could you tell me what is module"override"?I can't fint it and download it by "conda" or "pip".

**Comment by aishamina** [comment]
> Excuses me.When I run" train_models_sgcls.sh 2"，it goes wrong
> 
> Traceback (most recent call last):
> File "/home/lijiayi/neural-motifs-master/models/train_rels.py", line 27, in 
> from lib.rel_model import RelModel
> File "/home/lijiayi/neural-motifs-master/lib/rel_model.py", line 17, in 
> from lib.lstm.decoder_rnn import DecoderRNN
> File "/home/lijiayi/neural-motifs-master/lib/lstm/decoder_rnn.py", line 10, in 
> from .highway_lstm_cuda.alternating_highway_lstm import block_orthogonal
> File "/home/lijiayi/neural-motifs-master/lib/lstm/highway_lstm_cuda/alternating_highway_lstm.py", line 8, in 
> from overrides import overrides
> ModuleNotFoundError: No module named 'overrides'
> 
> Could you tell me what is module"overrides"?I can't fint it and download it by "conda" or "pip".

**Comment by aishamina** [comment]
Well...I can download it now.I am sorry to ask this silly question
